### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rngtng** [dancavallaro/rack-requestid#2]
Hey, can you please push a new release, so the latest change is included? cheers!

**Comment by dancavallaro** [comment]
Released as version 0.2: https://rubygems.org/gems/rack-requestid/versions/0.2

Thanks for the reminder; this was just a little hobby project and didn't realize anyone was using it, sorry I forgot to release the new version!

**Comment by soylent** [comment]
@dancavallaro, thank you!

**Comment by rngtng** [comment]
that was quick - awesome! thx
